from . import edi_config_table
from . import edi_config_table_line
from . import logs_details
from . import ftp_syncing
from . import ftp_attachment
from . import edi_transactions
from . import ftp_list
from . import sftp_syncing
from . import ir_cron
from . import translation_table
